pkgfile: update() updated.
It will now alert the user as to which repo is used
if the --verbose flag is given

diff --git a/pkgfile b/pkgfile
--- a/pkgfile
+++ b/pkgfile
@@ -24,7 +24,7 @@ fi
 ###
 # You should not change below this point
 ##
-MYVERSION=3.0
+MYVERSION=3.1
 SEARCHTARGET=
 ACTIONS=()
 REGEX=
@@ -101,8 +101,11 @@ update () {
                 if [ ! -w "$FILELIST_DIR" ];then
                         die 1 "No write permission to %s, try somewhere else\n" "$FILELIST_DIR"
                 fi
-                cd "$FILELIST_DIR"
+                cd "$FILELIST_DIR" || die 1 "Unable to change directory to %s\n" $FILELIST_DIR
                 rm -f "$repofile"
+                if [ "$VERBOSE" -eq 1 ]; then
+                        msg "Using mirror %s... " $mirror
+                fi
                 msg "Updating %s file list... " $repo
                 wget -q  --limit-rate="$RATELIMIT" "$filelist" || (warn "Could not retrieve %s\n" $filelist; continue)
                 msg "Extracting file list... " $repo
