newpkg: Complete rewrite to use a modular system.
newpkg will run any defined "presets"; default.preset if none is given.
Presets may define two things: copies and modifications. Common sets of
those are split into "actions" -- modular building blocks. The default
preset includes the 'pkgbuild' action, which defines one copy (The proto
PKGBUILD), and several modifications (setting pkgname, contributor,
stripping boilerplate comments, so on). This system allows for a very
flexible creation process which I hope to make even better in the
future. An interactive preset similar to debian's dh_make should be easy
to add.

Once the preset is sourced and any actions defined either in that preset
or by the user on the command line, newpkg does 3 things;
1) Make the pkgbuild directory
2) Copy all defined files into it
3) Run all defined modifications

For now, command line options are translated to their
equivalents from the old version, but they are not guaranteed to stay
the same.

New options added are -a (--action) and -P (--preset).

diff --git a/scripts/newpkg b/scripts/newpkg
--- a/scripts/newpkg
+++ b/scripts/newpkg
@@ -25,6 +25,7 @@ CONTRIB_INFO=
 BASEDIR="${HOME}/builds"
 CONFIG_DIR='/etc/pkgtools/'
 PKGTOOLS_DIR='/usr/share/pkgtools/'
+PRESET_DIR="$PKGTOOLS_DIR/newpkg/presets"
 
 if [[ -r $PKGTOOLS_DIR/functions ]]; then
     . $PKGTOOLS_DIR/functions
@@ -32,8 +33,8 @@ else
     printf "Unable to source function file!\n" >&2
     exit 1
 fi
-if [ -r /usr/share/pkgtools/functions.newpkg ]; then
-    source /usr/share/pkgtools/functions.newpkg
+if [[ -r $PKGTOOLS_DIR/functions.newpkg ]]; then
+    . $PKGTOOLS_DIR/functions.newpkg
 else
     printf "Unable to source newpkg function file!\n" >&2
     exit 1
@@ -47,14 +48,12 @@ PROGNAME="$(basename $0)"
 
 PROTODIR='/usr/share/pacman'
 
-ACTIONS=()       # Better than $DOFOO TODO
-#ACTIONS=(pkgbuild installfile rcd abs)
-DOCOPYPKGBUILD=1 # Copy the prototype PKGBUILD
-DOCOPYINSTALL=0  # Copy the .install file
+declare -A ACTIONS
+declare -a MODIFICATIONS
+declare -A COPIES
+PRESET=default
 DOABS=0      # Copy from ABS instead of normal operation TODO
 ABSROOT='/var/abs'
-DOCOPYRC=0       # Copy the prototype rc.d script
-DOFORCE=0    # Overwrite existing files
 
 load_config 'newpkg.conf'
 
@@ -64,13 +63,14 @@ function usage {
     msg "%s version %s -- A script to speed up creating new PKGBUILDs\n" "$PROGNAME" "$MYVERSION"
     msg "Usage: %s [options] PKGNAME\n" "$PROGNAME"
     msg "Options:\n"
+    msg "    -a --action        - Add a modular action to the creation.\n"
+    msg "                         Call multiple times for multiple actions\n"
     msg "    -h --help          - Print this usage\n"
-    msg "    -f --force         - Overwrite existing files in the target dir\n"
     msg "    -i --install-file  - Copy the prototype .install file\n"
     msg "    --rc               - Copy the protype for an rc.d script\n"
     msg "    -p --pkgbuild      - Specify the PKGBUILD file. If not absolute, the\n"
     msg "                         filename is relative to %s.\n" "$PROGNAME"
-    msg "                         Use '-' to not copy any PKGBUILD\n"
+    msg "    -P --preset        - Use the specified modular preset\n"
     msg "    --sf --sourceforge - Set url and source to common Sourceforge urls\n"
     msg "    --split            - Create a split PKGBUILD\n"
     msg "    --cvs              - Create a cvs PKGBUILD\n"
@@ -81,89 +81,68 @@ function usage {
 }
 # }}}
 
-# maketargetdir() {{{
-maketargetdir () {
-    if [ -d "$pkgdir" ]; then
-        if [ "$DOFORCE" -eq 1 ]; then
-            warn "%s already exists in %s -- continuing anyway!\n" $pkgname $BASEDIR 
-        else
-            die 1 "%s already exists in %s -- aborting\n" $pkgname $BASEDIR
-        fi
-    else
-        mkdir -p "$pkgdir" || die 1 "Unable to create directory %s" "$pkgdir"
-        msg "Creating package dir for %s\n" $pkgname
-    fi
+# make_pkgdir() {{{
+make_pkgdir () {
+    mkdir -p "$pkgdir" || die 1 "Unable to create directory %s" "$pkgdir"
+    msg "Creating package dir for %s\n" $pkgname
+
+    cd "$pkgdir" || die 1 "Can't cd to %s!\n" "$pkgdir"
 }
 # }}}
 
-# copypkgbuild() {{{
-copypkgbuild () {
-    if [ -r "$PROTO_PKGBUILD" ]; then
-        msg "Copying prototype PKGBUILD\n"
-        cp "$PROTO_PKGBUILD" ./PKGBUILD || die 1 "Unable to copy PKGBUILD prototype\n"
-        sed -i "s#^pkgname=.*#pkgname=$pkgname#" PKGBUILD
-
-        sed -i '/^# This is an example PKGBUILD/d' PKGBUILD
-        sed -i '/^# and remove these comments/d' PKGBUILD
-        sed -i '/^# NOTE: Please fill out/d' PKGBUILD
-        sed -i '/^# then please put/d' PKGBUILD
-        sed -i '/^# This is an example of a/d' PKGBUILD
-        sed -i '/^# start to creating your/d' PKGBUILD
-        sed -i "/^# see 'man PKGBUILD'. NOTE/d" PKGBUILD
-        sed -i '/^# If it is unknown, then/d' PKGBUILD
-
-        [ -n "$CONTRIB_INFO" ] && sed -i "s/^# Contributor: .*/# Contributor: $CONTRIB_INFO/" PKGBUILD
-
-        if [ "$SFURL" -eq 1 ]; then
-            sed -i 's#$pkgname-$pkgver.tar.gz#http://downloads.sourceforge.net/$pkgname/$pkgname-$pkgver.tar.gz#' $pkgdir/PKGBUILD
-            sed -i 's#url=""#url="http://$pkgname.sourceforge.net"#' $pkgdir/PKGBUILD
-        fi
-    else
-        warn "Could not find prototype PKGBUILD '%s'\n" "$PROTO_PKGBUILD"
-    fi
+# copy_files() {{{
+copy_files() {
+    for file in "${!COPIES[@]}"; do
+        cp "${COPIES[$file]}" "$file"
+    done
 }
 # }}}
 
-# copyinstallfile() {{{
-copyinstallfile () {
-    if [ -r "$PROTO_INSTALL" ]; then 
-        msg "Copying prototype .install file\n"
-        cp "$PROTO_INSTALL" "./${pkgname}.install"
-        if [ -w PKGBUILD ]; then
-            sed -i "s#^install=.*#install='${pkgname}.install'#" PKGBUILD
-        fi
-    else
-        warn "Could not find prototype .install\n"
-    fi
+# modify_files() {{{
+modify_files() {
+    for mod in "${MODIFICATIONS[@]}"; do
+        [[ $(type -t $mod) == 'function' ]] || continue
+        $mod
+    done
 }
 # }}}
 
-if [ -z "$1" ]; then
+
+if [[ -z "$1" ]]; then
     usage
 fi
 
-while [ "$#" -ne 0 ]; do
+while (( $# != 0 )); do
     case $1 in
-        -h|--help) 
+        -a|--action)
+            if [[ -z $2 ]]; then
+                die 1 "%s %s option requires a parameter!\n" "$PROGNAME" "$1"
+            fi
+            add_action $2
+            ;;
+        -h|--help)
             usage
             ;;
-        -i|--install-file)     
-            DOCOPYINSTALL=1
+        -i|--install-file)
+            add_action install
             ;;
         --rc)
-            DOCOPYRC=1
-            ;;
-        -f|--force)
-            DOFORCE=1
+            add_action rcd
             ;;
         -p|--pkgbuild)
-            if [ -z "$2" ]; then
+            if [[ -z $2 ]]; then
                 die 1 "%s %s option requires a parameter!\n" "$PROGNAME" "$1"
             fi
             setpkgbuild "$2"; shift
             ;;
+        -P|--preset)
+            if [[ -z $2 ]]; then
+                die 1 "%s %s option requires a parameter!\n" "$PROGNAME" "$1"
+            fi
+            PRESET=$2; shift
+            ;;
         --sf|--sourceforge)
-            SFURL=1
+            add_action sf
             ;;
         --split)
             setpkgbuild "PKGBUILD-split.proto"
@@ -183,30 +162,33 @@ while [ "$#" -ne 0 ]; do
         -*)
             die 1 "Unrecognized option %s\n" "$1"
             ;;
-        *)      
+        *)
             pkgname=$(echo $1 | sed 's; ;;g' | sed 's;/$;;')
             ;;
     esac
     shift
 done
 
-[ -z "$pkgname" ] && die 1 "No package name supplied\n"
+[[ -z $pkgname ]] && die 1 "No package name supplied\n"
 pkgdir="${BASEDIR}/${pkgname}"
 
-maketargetdir
-cd "$pkgdir" || die 1 "Unable to change directory to %s\n" "$pkgdir"
-
-if [ "$DOCOPYPKGBUILD" -eq 1 ]; then
-    copypkgbuild
+if [[ -r $PRESET_DIR/$PRESET.preset ]]; then
+    . "$PRESET_DIR/$PRESET.preset"
+else
+    die 1 "Can't read preset '%s' in '%s'\n" "$PRESET" "$PRESET_DIR"
 fi
 
-if [ "$DOCOPYINSTALL" -eq 1 ]; then
-    copyinstallfile
-fi
+for act in ${!ACTIONS[@]}; do
+    if [[ -r $PRESET_DIR/$act.action ]]; then
+        . "$PRESET_DIR/$act.action"
+    else
+        die 1 "Can't read action '%s' in '%s'\n" "$act" "$PRESET_DIR"
+    fi
+done
 
-if [ "$DOCOPYRC" -eq 1 ]; then
-    copyrcd
-fi
+make_pkgdir
+copy_files
+modify_files
 
 msg "All done! New package prepared in %s\n" $pkgdir
 quit 0
