pkgfile: Skip processing if a repo doesn't have a file list
Signed-off-by: Daenyth <Daenyth+github@gmail.com>

diff --git a/scripts/pkgfile b/scripts/pkgfile
--- a/scripts/pkgfile
+++ b/scripts/pkgfile
@@ -52,7 +52,7 @@ fi
 if [ -r "${HOME}/.pkgtools/pkgfile.conf" ]; then
         source "${HOME}/.pkgtools/pkgfile.conf"
 fi
-readonly MYVERSION=7.0
+readonly MYVERSION=8.0
 SEARCHTARGET=
 ACTION=
 UPDATE=0
@@ -146,10 +146,10 @@ update () {
                         msg "\nUsing mirror %s... \n" $mirror
                 fi
                 rm -f "$repofile"
-                wget -q  --limit-rate="$RATELIMIT" "$filelist" || (warn "Could not retrieve %s\n" $filelist; continue)
+                wget -q  --limit-rate="$RATELIMIT" "$filelist" || { warn "Could not retrieve %s\n" $filelist; continue; }
                 msg "Extracting %s file list... " $repo
-                mkdir -p "$repo.tmp" || (warn "Could not create directory for %s\n" $repo; continue)
-                tar ozxf "$repofile" -C "$repo.tmp" 2> /dev/null || (warn "Unable to extract %s\n" $repofile; continue)
+                mkdir -p "$repo.tmp" || { warn "Could not create temporary directory for %s\n" $repo; continue; }
+                tar ozxf "$repofile" -C "$repo.tmp" 2> /dev/null || { warn "Unable to extract %s\n" $repofile; continue; }
                 rm -rf "$repo"
                 mv "$repo.tmp" "$repo"
                 rm -f "$repofile"
